# Generated by Django 5.2.3 on 2025-09-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_paquetes_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientosBus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vip', models.BooleanField(default=False)),
                ('reservado', models.BooleanField(default=False)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo_km', models.IntegerField()),
                ('capacidad_bus', models.IntegerField(default=1)),
                ('asientos_vip', models.IntegerField(default=0)),
                ('asientos_general', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='paquetes',
            name='vuelo_vuelta',
        ),
        migrations.RemoveField(
            model_name='paquetes',
            name='vuelo_ida',
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='asiento_ida',
            field=models.ManyToManyField(blank=True, related_name='paquetes_asiento_ida', to='api.asientosbus'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='asiento_vuelta',
            field=models.ManyToManyField(blank=True, related_name='paquetes_asiento_vuelta', to='api.asientosbus'),
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('distancia_km', models.IntegerField(default=0)),
                ('precio_base', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viajes', to='api.buses')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viajes_destino', to='api.ciudades')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viajes_orig', to='api.ciudades')),
            ],
        ),
        migrations.AddField(
            model_name='asientosbus',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asientos_bus', to='api.viajes'),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='viaje_ida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes_ida', to='api.viajes'),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='viaje_vuelta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes_vuelta', to='api.viajes'),
        ),
        migrations.DeleteModel(
            name='Asientos',
        ),
        migrations.DeleteModel(
            name='Aviones',
        ),
        migrations.DeleteModel(
            name='Vuelos',
        ),
    ]
